name: Trigger auto deployment for roll-dice-api-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/roll-dice-api-container-AutoDeployTrigger-69ef0868-46cc-49a4-9313-d36bf04db065.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ROLLDICEAPICONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: rollcontainerregistrytest.azurecr.io
          registryUsername: ${{ secrets.ROLLDICEAPICONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ROLLDICEAPICONTAINER_REGISTRY_PASSWORD }}
          containerAppName: roll-dice-api-container
          resourceGroup: rg-startse-test-001
          imageToBuild: rollcontainerregistrytest.azurecr.io/roll-dice-api-container:${{ github.sha }}
          

     

